# Generated by Django 2.1.4 on 2019-01-01 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    #initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('gasstationid', models.PositiveSmallIntegerField(db_column='gasStationID', primary_key=True, serialize=False)),
                ('gasstationlat', models.DecimalField(blank=True, db_column='gasStationLat', decimal_places=7, max_digits=10, null=True)),
                ('gasstationlong', models.DecimalField(blank=True, db_column='gasStationLong', decimal_places=7, max_digits=10, null=True)),
                ('fuelcompid', models.IntegerField(db_column='fuelCompID')),
                ('fuelcompnormalname', models.CharField(db_column='fuelCompNormalName', max_length=45)),
                ('gasstationowner', models.CharField(db_column='gasStationOwner', max_length=128)),
                ('ddid', models.CharField(db_column='ddID', max_length=10)),
                ('ddnormalname', models.CharField(db_column='ddNormalName', max_length=45)),
                ('municipalityid', models.CharField(db_column='municipalityID', max_length=10)),
                ('municipalitynormalname', models.CharField(db_column='municipalityNormalName', max_length=45)),
                ('countyid', models.CharField(db_column='countyID', max_length=10)),
                ('countyname', models.CharField(db_column='countyName', max_length=64)),
                ('gasstationaddress', models.CharField(blank=True, db_column='gasStationAddress', max_length=255, null=True)),
                ('phone1', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gasstations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.IntegerField(db_column='orderID', primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('when', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('productid', models.AutoField(db_column='productID', primary_key=True, serialize=False)),
                ('fueltypeid', models.PositiveIntegerField(db_column='fuelTypeID')),
                ('fuelsubtypeid', models.PositiveIntegerField(db_column='fuelSubTypeID')),
                ('fuelnormalname', models.CharField(db_column='fuelNormalName', max_length=64)),
                ('fuelname', models.CharField(db_column='fuelName', max_length=128)),
                ('fuelprice', models.DecimalField(db_column='fuelPrice', decimal_places=3, max_digits=4)),
                ('dateupdated', models.DateTimeField(blank=True, db_column='dateUpdated', null=True)),
                ('ispremium', models.IntegerField(blank=True, db_column='isPremium', null=True)),
                ('gasstation', models.ForeignKey(db_column='gasStationID', on_delete=django.db.models.deletion.DO_NOTHING, to='fuels.GasStation')),
            ],
            options={
                'db_table': 'pricedata',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='productid',
            field=models.ForeignKey(db_column='productID', on_delete=django.db.models.deletion.DO_NOTHING, to='fuels.PriceData'),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pricedata',
            unique_together={('gasstation', 'fueltypeid', 'fuelsubtypeid')},
        ),
    ]
