# Generated by Django 2.1.4 on 2019-01-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190101_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='geo@gmail.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
